// Church Service - Handles API calls for church management

import { AuthService } from './auth';
import { Conference, Union, Church } from '../types/rbac';
import { 
  ChurchListResponse, 
  ChurchResponse,
  CreateChurchData, 
  UpdateChurchData,
  ChurchListParams,
} from '../types/hierarchy';

const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL;

export class ChurchService {
  private static getAuthHeaders() {
    const token = AuthService.getToken();
    return {
      'Content-Type': 'application/json',
      Authorization: token ? `Bearer ${token}` : '',
    };
  }

  /**
   * Get all churches
   */
  static async getAllChurches(params?: ChurchListParams): Promise<ChurchListResponse> {
    try {
      const queryParams = new URLSearchParams();
      
      if (params?.conferenceId) {
        queryParams.append('conferenceId', params.conferenceId);
      }
      if (params?.unionId) {
        queryParams.append('unionId', params.unionId);
      }
      if (params?.isActive !== undefined) {
        queryParams.append('isActive', params.isActive.toString());
      }
      if (params?.search) {
        queryParams.append('search', params.search);
      }
      if (params?.limit) {
        queryParams.append('limit', params.limit.toString());
      }
      if (params?.offset) {
        queryParams.append('offset', params.offset.toString());
      }

      const url = `${API_BASE_URL}/api/churches${queryParams.toString() ? `?${queryParams.toString()}` : ''}`;
      
      const response = await fetch(url, {
        method: 'GET',
        headers: this.getAuthHeaders(),
      });

      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: ${response.statusText}`);
      }

      return await response.json();
    } catch (error) {
      console.error('Error fetching churches:', error);
      throw new Error(
        error instanceof Error ? error.message : 'Failed to fetch churches'
      );
    }
  }

  /**
   * Get church by ID
   */
  static async getChurchById(id: string): Promise<ChurchResponse> {
    try {
      const response = await fetch(`${API_BASE_URL}/api/churches/${id}`, {
        method: 'GET',
        headers: this.getAuthHeaders(),
      });

      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: ${response.statusText}`);
      }

      return await response.json();
    } catch (error) {
      console.error('Error fetching church:', error);
      throw new Error(
        error instanceof Error ? error.message : 'Failed to fetch church'
      );
    }
  }

  /**
   * Create new church
   */
  static async createChurch(data: CreateChurchData): Promise<ChurchResponse & {
    codeAutoGenerated?: boolean;
    generatedCode?: string;
  }> {
    try {
      const response = await fetch(`${API_BASE_URL}/api/churches`, {
        method: 'POST',
        headers: this.getAuthHeaders(),
        body: JSON.stringify(data),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.message || `HTTP ${response.status}: ${response.statusText}`);
      }

      return await response.json();
    } catch (error) {
      console.error('Error creating church:', error);
      throw new Error(
        error instanceof Error ? error.message : 'Failed to create church'
      );
    }
  }

  /**
   * Update church
   */
  static async updateChurch(id: string, data: UpdateChurchData): Promise<ChurchResponse> {
    try {
      const response = await fetch(`${API_BASE_URL}/api/churches/${id}`, {
        method: 'PUT',
        headers: this.getAuthHeaders(),
        body: JSON.stringify(data),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.message || `HTTP ${response.status}: ${response.statusText}`);
      }

      return await response.json();
    } catch (error) {
      console.error('Error updating church:', error);
      throw new Error(
        error instanceof Error ? error.message : 'Failed to update church'
      );
    }
  }

  /**
   * Delete church
   */
  static async deleteChurch(id: string): Promise<{ success: boolean; message: string }> {
    try {
      const response = await fetch(`${API_BASE_URL}/api/churches/${id}`, {
        method: 'DELETE',
        headers: this.getAuthHeaders(),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.message || `HTTP ${response.status}: ${response.statusText}`);
      }

      return await response.json();
    } catch (error) {
      console.error('Error deleting church:', error);
      throw new Error(
        error instanceof Error ? error.message : 'Failed to delete church'
      );
    }
  }

  /**
   * Upload banner image for church
   */
  static async updateChurchBanner(churchId: string, file: File, alt?: string): Promise<{
    success: boolean;
    message: string;
    data?: { 
      image: {
        url: string;
        key: string;
        alt: string;
        mediaFileId?: string;
        thumbnailUrl?: string;
      }
    };
  }> {
    try {
      const formData = new FormData();
      formData.append('banner', file);
      if (alt) {
        formData.append('alt', alt);
      }

      const response = await fetch(`${API_BASE_URL}/api/churches/${churchId}/banner`, {
        method: 'PUT',
        headers: {
          Authorization: this.getAuthHeaders().Authorization,
        },
        body: formData,
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.message || `HTTP ${response.status}: ${response.statusText}`);
      }

      return await response.json();
    } catch (error) {
      console.error('Error uploading church banner:', error);
      throw new Error(
        error instanceof Error ? error.message : 'Failed to upload church banner'
      );
    }
  }

  /**
   * Set church banner from existing media file
   */
  static async updateChurchBannerWithMediaFile(churchId: string, mediaFileId: string, alt?: string): Promise<{
    success: boolean;
    message: string;
    data?: { 
      image: {
        url: string;
        key: string;
        alt: string;
        mediaFileId?: string;
        thumbnailUrl?: string;
      }
    };
  }> {
    try {
      const response = await fetch(`${API_BASE_URL}/api/churches/${churchId}/banner/media`, {
        method: 'PUT',
        headers: this.getAuthHeaders(),
        body: JSON.stringify({
          mediaFileId,
          alt: alt || '',
        }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.message || `HTTP ${response.status}: ${response.statusText}`);
      }

      return await response.json();
    } catch (error) {
      console.error('Error setting church banner from media:', error);
      throw new Error(
        error instanceof Error ? error.message : 'Failed to set church banner from media'
      );
    }
  }

  /**
   * Get church statistics
   */
  static async getChurchStatistics(id: string): Promise<{
    success: boolean;
    data: {
      membership?: {
        total?: number;
        baptized?: number;
        visiting?: number;
      };
      averageAttendance?: number;
      ageGroups?: {
        children?: number;
        youth?: number;
        adults?: number;
        seniors?: number;
      };
      teams?: number;
      services?: number;
      events?: number;
    };
  }> {
    try {
      const response = await fetch(`${API_BASE_URL}/api/churches/${id}/statistics`, {
        method: 'GET',
        headers: this.getAuthHeaders(),
      });

      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: ${response.statusText}`);
      }

      return await response.json();
    } catch (error) {
      console.error('Error fetching church statistics:', error);
      throw new Error(
        error instanceof Error ? error.message : 'Failed to fetch church statistics'
      );
    }
  }

  /**
   * Get church hierarchy
   */
  static async getChurchHierarchy(id: string): Promise<{
    success: boolean;
    data: {
      church: Church;
      conference?: Conference;
      union?: Union;
      hierarchyPath: string;
      level: number;
    };
  }> {
    try {
      const response = await fetch(`${API_BASE_URL}/api/churches/${id}/hierarchy`, {
        method: 'GET',
        headers: this.getAuthHeaders(),
      });

      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: ${response.statusText}`);
      }

      return await response.json();
    } catch (error) {
      console.error('Error fetching church hierarchy:', error);
      throw new Error(
        error instanceof Error ? error.message : 'Failed to fetch church hierarchy'
      );
    }
  }
}