'use client';

import React, { useState, useRef, useEffect } from 'react';
import Image from 'next/image';
import Modal, { ModalBody, ModalFooter } from './Modal';
import MediaLibraryModal from './MediaLibraryModal';
import { ChurchService } from '@/lib/churchService';
import { ConferenceService } from '@/lib/conferenceService';
import { Church } from '@/types/hierarchy';
import { Conference } from '@/types/rbac';
import { MediaFile } from '@/lib/mediaService';
import { useToast } from '@/contexts/ToastContext';
import { CloudArrowUpIcon, XMarkIcon, PhotoIcon } from '@heroicons/react/24/outline';

interface ChurchModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (savedChurch: Church, isEdit: boolean) => void;
  church?: Church | null;
}

export default function ChurchModal({ 
  isOpen, 
  onClose, 
  onSave, 
  church
}: ChurchModalProps) {
  const [formData, setFormData] = useState({
    name: church?.name || '',
    code: church?.code || '',
    conferenceId: typeof church?.conferenceId === 'object' && church?.conferenceId ? (church.conferenceId as Conference)._id : church?.conferenceId || '',
    location: {
      address: {
        address: church?.location?.address?.address || '',
        city: church?.location?.address?.city || '',
        state: church?.location?.address?.state || '',
        country: church?.location?.address?.country || '',
        postalCode: church?.location?.address?.postalCode || ''
      }
    },
    contact: {
      email: church?.contact?.email || '',
      phone: church?.contact?.phone || '',
      website: church?.contact?.website || ''
    },
  });
  const [conferences, setConferences] = useState<Conference[]>([]);
  const [loading, setLoading] = useState(false);
  const [codeAutoGenerated, setCodeAutoGenerated] = useState(false);
  const [bannerImage, setBannerImage] = useState<File | null>(null);
  const [bannerPreview, setBannerPreview] = useState<string | null>(church?.primaryImage?.url || null);
  const [bannerAlt, setBannerAlt] = useState(church?.primaryImage?.alt || '');
  const [selectedMediaFile, setSelectedMediaFile] = useState<MediaFile | null>(null);
  const [isMediaLibraryOpen, setIsMediaLibraryOpen] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const toast = useToast();

  // Fetch conferences for dropdown
  useEffect(() => {
    const fetchConferences = async () => {
      try {
        const response = await ConferenceService.getAllConferences();
        if (response.success && response.data) {
          setConferences(response.data);
        }
      } catch (error) {
        console.error('Error fetching conferences:', error);
      }
    };

    if (isOpen) {
      fetchConferences();
    }
  }, [isOpen]);

  // Image handling functions
  const handleImageUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      // Validate file type
      if (!file.type.startsWith('image/')) {
        toast.error('Invalid file type', 'Please select an image file (JPEG, PNG, WebP).');
        return;
      }

      // Validate file size (2MB limit)
      if (file.size > 2 * 1024 * 1024) {
        toast.error('File too large', 'Banner image must be smaller than 2MB.');
        return;
      }

      setBannerImage(file);
      
      // Create preview
      const reader = new FileReader();
      reader.onload = (e) => {
        setBannerPreview(e.target?.result as string);
      };
      reader.readAsDataURL(file);
    }
  };

  const removeBannerImage = () => {
    setBannerImage(null);
    setSelectedMediaFile(null);
    setBannerPreview(church?.primaryImage?.url || null);
    setBannerAlt(church?.primaryImage?.alt || '');
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  const handleMediaSelect = (mediaFile: MediaFile) => {
    setSelectedMediaFile(mediaFile);
    setBannerPreview(mediaFile.url);
    setBannerAlt(mediaFile.alt);
    setBannerImage(null); // Clear any previously selected file
    setIsMediaLibraryOpen(false);
  };

  const openMediaLibrary = () => {
    setIsMediaLibraryOpen(true);
  };

  // Helper function to provide user-friendly error messages
  const getUserFriendlyErrorMessage = (errorMessage: string) => {
    const lowerMessage = errorMessage.toLowerCase();
    
    if (lowerMessage.includes('name') && lowerMessage.includes('required')) {
      return 'Church name is required. Please enter a name for the church.';
    }
    
    if (lowerMessage.includes('conference') && lowerMessage.includes('required')) {
      return 'Conference is required. Please select a parent conference.';
    }
    
    if (lowerMessage.includes('code') && lowerMessage.includes('exist')) {
      return 'A church with this code already exists in the selected conference. Please choose a different code.';
    }
    
    if (lowerMessage.includes('email') && lowerMessage.includes('invalid')) {
      return 'Please enter a valid email address.';
    }
    
    if (lowerMessage.includes('permission') || lowerMessage.includes('authorized')) {
      return 'You do not have permission to perform this action. Please contact your administrator.';
    }
    
    return errorMessage || 'An unexpected error occurred. Please try again.';
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    try {
      setLoading(true);
      
      const churchData = {
        name: formData.name,
        code: formData.code || undefined,
        conferenceId: formData.conferenceId,
        location: formData.location,
        contact: formData.contact
      };

      let response;
      if (church) {
        // Update existing church
        response = await ChurchService.updateChurch(church._id, churchData);
        
        // Handle banner image update if changed
        if ((bannerImage || selectedMediaFile) && response.success && response.data) {
          console.log('Updating banner for church:', response.data.name, {
            hasFile: !!bannerImage,
            hasMediaFile: !!selectedMediaFile,
            mediaFileId: selectedMediaFile?._id
          });
          
          try {
            let bannerResponse;
            if (bannerImage) {
              // Upload new file
              console.log('Uploading new banner file...');
              bannerResponse = await ChurchService.updateChurchBanner(response.data._id, bannerImage, bannerAlt);
            } else if (selectedMediaFile) {
              // Update with selected media file
              console.log('Setting banner from media file:', selectedMediaFile._id);
              bannerResponse = await ChurchService.updateChurchBannerWithMediaFile(response.data._id, selectedMediaFile._id, bannerAlt);
            }
            
            console.log('Banner update response:', bannerResponse);
            console.log('Banner response data:', JSON.stringify(bannerResponse?.data, null, 2));
            
            if (bannerResponse?.success) {
              console.log('Banner update successful, constructing primaryImage...');
              
              let primaryImage = null;
              
              // Try to get image data from API response first
              if (bannerResponse.data?.image) {
                primaryImage = {
                  url: bannerResponse.data.image.url,
                  thumbnailUrl: bannerResponse.data.image.url,
                  key: bannerResponse.data.image.key,
                  alt: bannerResponse.data.image.alt || bannerAlt,
                  mediaFileId: bannerResponse.data.image.mediaFileId
                };
                console.log('Constructed primaryImage from API response:', primaryImage);
              }
              // If API returns no data (204), construct from selectedMediaFile
              else if (selectedMediaFile) {
                primaryImage = {
                  url: selectedMediaFile.url,
                  thumbnailUrl: selectedMediaFile.thumbnail?.url || selectedMediaFile.url,
                  key: selectedMediaFile.key,
                  alt: bannerAlt || selectedMediaFile.alt || '',
                  mediaFileId: selectedMediaFile._id
                };
                console.log('Constructed primaryImage from selectedMediaFile:', primaryImage);
              }
              
              if (primaryImage) {
                // Fetch the updated church data and add the primaryImage
                const updatedChurchResponse = await ChurchService.getChurchById(response.data._id);
                if (updatedChurchResponse.success && updatedChurchResponse.data) {
                  // Manually add the primaryImage to the church object since the API doesn't return it
                  updatedChurchResponse.data.primaryImage = primaryImage;
                  response.data = updatedChurchResponse.data;
                  console.log('Church object now has primaryImage:', !!response.data.primaryImage);
                }
              }
            }
          } catch (bannerError) {
            console.error('Banner update error:', bannerError);
            toast.error('Banner upload failed', 'Church updated but banner image could not be uploaded.');
          }
        }
      } else {
        // Create new church
        response = await ChurchService.createChurch(churchData);
        
        // Handle banner image upload for new church
        if ((bannerImage || selectedMediaFile) && response.success && response.data) {
          try {
            let bannerResponse;
            if (bannerImage) {
              // Upload new file
              bannerResponse = await ChurchService.updateChurchBanner(response.data._id, bannerImage, bannerAlt);
            } else if (selectedMediaFile) {
              // Update with selected media file
              bannerResponse = await ChurchService.updateChurchBannerWithMediaFile(response.data._id, selectedMediaFile._id, bannerAlt);
            }
            
            if (bannerResponse?.success) {
              let primaryImage = null;
              
              // Try to get image data from API response first
              if (bannerResponse.data?.image) {
                primaryImage = {
                  url: bannerResponse.data.image.url,
                  thumbnailUrl: bannerResponse.data.image.url,
                  key: bannerResponse.data.image.key,
                  alt: bannerResponse.data.image.alt || bannerAlt,
                  mediaFileId: bannerResponse.data.image.mediaFileId
                };
              }
              // If API returns no data (204), construct from selectedMediaFile
              else if (selectedMediaFile) {
                primaryImage = {
                  url: selectedMediaFile.url,
                  thumbnailUrl: selectedMediaFile.thumbnail?.url || selectedMediaFile.url,
                  key: selectedMediaFile.key,
                  alt: bannerAlt || selectedMediaFile.alt || '',
                  mediaFileId: selectedMediaFile._id
                };
              }
              
              if (primaryImage) {
                // Fetch the updated church data and add the primaryImage
                const updatedChurchResponse = await ChurchService.getChurchById(response.data._id);
                if (updatedChurchResponse.success && updatedChurchResponse.data) {
                  // Manually add the primaryImage to the church object since the API doesn't return it
                  updatedChurchResponse.data.primaryImage = primaryImage;
                  response.data = updatedChurchResponse.data;
                }
              }
            }
          } catch (bannerError) {
            console.warn('Failed to upload banner image:', bannerError);
            toast.error('Banner upload failed', 'Church created but banner image could not be uploaded.');
          }
        }
      }
      
      if (response.success && response.data) {
        // Handle auto-generated code notification
        const extendedResponse = response as typeof response & {
          codeAutoGenerated?: boolean;
          generatedCode?: string;
        };
        if (extendedResponse.codeAutoGenerated && extendedResponse.generatedCode && !church) {
          setFormData(prev => ({ ...prev, code: extendedResponse.generatedCode || '' }));
          setCodeAutoGenerated(true);
          toast.success(
            'Church created with auto-generated code',
            `Church code "${extendedResponse.generatedCode}" was automatically assigned.`
          );
        }
        
        onSave(response.data, !!church);
      } else {
        const errorMessage = response.message || 'An unknown error occurred';
        const userFriendlyMessage = getUserFriendlyErrorMessage(errorMessage);
        
        toast.error(
          church ? 'Failed to update church' : 'Failed to create church',
          userFriendlyMessage
        );
      }
    } catch (error) {
      console.error('Error saving church:', error);
      
      let errorMessage = 'An unexpected error occurred';
      if (error instanceof Error) {
        errorMessage = error.message;
      } else if (typeof error === 'string') {
        errorMessage = error;
      }
      
      const userFriendlyMessage = getUserFriendlyErrorMessage(errorMessage);
      
      toast.error(
        church ? 'Failed to update church' : 'Failed to create church',
        userFriendlyMessage
      );
    } finally {
      setLoading(false);
    }
  };

  // Reset form when church changes or modal opens/closes
  React.useEffect(() => {
    if (isOpen) {
      setFormData({
        name: church?.name || '',
        code: church?.code || '',
        conferenceId: typeof church?.conferenceId === 'object' && church?.conferenceId ? (church.conferenceId as Conference)._id : church?.conferenceId || '',
            location: {
          address: {
            address: church?.location?.address?.address || '',
            city: church?.location?.address?.city || '',
            state: church?.location?.address?.state || '',
            country: church?.location?.address?.country || '',
            postalCode: church?.location?.address?.postalCode || ''
          }
        },
        contact: {
          email: church?.contact?.email || '',
          phone: church?.contact?.phone || '',
          website: church?.contact?.website || ''
        }
      });
      
      // Reset image state
      console.log('ChurchModal initialization for:', church?.name, {
        hasPrimaryImage: !!church?.primaryImage,
        primaryImageUrl: church?.primaryImage?.url,
        primaryImageData: church?.primaryImage
      });
      
      setBannerImage(null);
      setSelectedMediaFile(null);
      setBannerPreview(church?.primaryImage?.url || null);
      setBannerAlt(church?.primaryImage?.alt || '');
      setCodeAutoGenerated(false);
      if (fileInputRef.current) {
        fileInputRef.current.value = '';
      }
    }
  }, [church, isOpen]);

  return (
    <>
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title={church ? 'Edit Church' : 'Create Church'}
      maxWidth="2xl"
    >
      <form onSubmit={handleSubmit}>
        <ModalBody className="space-y-6">
          {/* Basic Info */}
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700">
                Church Name *
              </label>
              <input
                type="text"
                value={formData.name}
                onChange={(e) => setFormData(prev => ({ ...prev, name: e.target.value }))}
                placeholder="Enter church name"
                required
                className="mt-1 block w-full px-4 py-3 text-base rounded-md border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700">
                Church Code
              </label>
              <div className="relative">
                <input
                  type="text"
                  value={formData.code}
                  onChange={(e) => {
                    setFormData(prev => ({ ...prev, code: e.target.value.toUpperCase() }));
                    setCodeAutoGenerated(false);
                  }}
                  placeholder={!church ? "Auto Generated" : "Enter church code"}
                  className={`mt-1 block w-full px-4 py-3 text-base rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 ${
                    codeAutoGenerated 
                      ? 'border-green-300 bg-green-50' 
                      : 'border-gray-300'
                  }`}
                />
                {codeAutoGenerated && (
                  <div className="absolute inset-y-0 right-0 flex items-center pr-3">
                    <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-green-100 text-green-800">
                      Auto-generated
                    </span>
                  </div>
                )}
              </div>
              {codeAutoGenerated && (
                <p className="mt-1 text-xs text-green-600">
                  This code was automatically generated based on your conference.
                </p>
              )}
            </div>
          </div>

          {/* Conference */}
          <div>
            <label className="block text-sm font-medium text-gray-700">
              Conference *
            </label>
            <select
              value={formData.conferenceId}
              onChange={(e) => setFormData(prev => ({ ...prev, conferenceId: e.target.value }))}
              required
              className="mt-1 block w-full px-4 py-3 text-base rounded-md border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500"
            >
              <option value="">Select a conference</option>
              {conferences.map((conference) => (
                <option key={conference._id} value={conference._id}>
                  {conference.name}
                </option>
              ))}
            </select>
          </div>


          {/* Location */}
          <div>
            <h4 className="text-sm font-medium text-gray-900 mb-4">Location</h4>
            
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700">
                  Address
                </label>
                <input
                  type="text"
                  value={formData.location.address.address}
                  onChange={(e) => setFormData(prev => ({ 
                    ...prev, 
                    location: { 
                      ...prev.location, 
                      address: { ...prev.location.address, address: e.target.value }
                    }
                  }))}
                  placeholder="Street address"
                  className="mt-1 block w-full px-4 py-3 text-base rounded-md border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700">
                  City
                </label>
                <input
                  type="text"
                  value={formData.location.address.city}
                  onChange={(e) => setFormData(prev => ({ 
                    ...prev, 
                    location: { 
                      ...prev.location, 
                      address: { ...prev.location.address, city: e.target.value }
                    }
                  }))}
                  placeholder="City"
                  className="mt-1 block w-full px-4 py-3 text-base rounded-md border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700">
                  State/Province
                </label>
                <input
                  type="text"
                  value={formData.location.address.state}
                  onChange={(e) => setFormData(prev => ({ 
                    ...prev, 
                    location: { 
                      ...prev.location, 
                      address: { ...prev.location.address, state: e.target.value }
                    }
                  }))}
                  placeholder="State or Province"
                  className="mt-1 block w-full px-4 py-3 text-base rounded-md border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700">
                  Country
                </label>
                <input
                  type="text"
                  value={formData.location.address.country}
                  onChange={(e) => setFormData(prev => ({ 
                    ...prev, 
                    location: { 
                      ...prev.location, 
                      address: { ...prev.location.address, country: e.target.value }
                    }
                  }))}
                  placeholder="Country"
                  className="mt-1 block w-full px-4 py-3 text-base rounded-md border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700">
                  Postal Code
                </label>
                <input
                  type="text"
                  value={formData.location.address.postalCode}
                  onChange={(e) => setFormData(prev => ({ 
                    ...prev, 
                    location: { 
                      ...prev.location, 
                      address: { ...prev.location.address, postalCode: e.target.value }
                    }
                  }))}
                  placeholder="Postal/ZIP code"
                  className="mt-1 block w-full px-4 py-3 text-base rounded-md border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500"
                />
              </div>
            </div>
          </div>

          {/* Contact Information */}
          <div>
            <h4 className="text-sm font-medium text-gray-900 mb-4">Contact Information</h4>
            
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700">
                  Email
                </label>
                <input
                  type="email"
                  value={formData.contact.email}
                  onChange={(e) => setFormData(prev => ({ 
                    ...prev, 
                    contact: { ...prev.contact, email: e.target.value }
                  }))}
                  placeholder="contact@church.org"
                  className="mt-1 block w-full px-4 py-3 text-base rounded-md border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700">
                  Phone
                </label>
                <input
                  type="tel"
                  value={formData.contact.phone}
                  onChange={(e) => setFormData(prev => ({ 
                    ...prev, 
                    contact: { ...prev.contact, phone: e.target.value }
                  }))}
                  placeholder="(123) 456-7890"
                  className="mt-1 block w-full px-4 py-3 text-base rounded-md border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500"
                />
              </div>

              <div className="col-span-2">
                <label className="block text-sm font-medium text-gray-700">
                  Website
                </label>
                <input
                  type="url"
                  value={formData.contact.website}
                  onChange={(e) => setFormData(prev => ({ 
                    ...prev, 
                    contact: { ...prev.contact, website: e.target.value }
                  }))}
                  placeholder="https://www.church.org"
                  className="mt-1 block w-full px-4 py-3 text-base rounded-md border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500"
                />
              </div>
            </div>
          </div>

          {/* Banner Image Upload */}
          <div>
            <h4 className="text-sm font-medium text-gray-900 mb-4">Banner Image</h4>
            
            {bannerPreview ? (
              <div className="relative">
                <div className="w-full h-32 bg-gray-100 rounded-lg overflow-hidden">
                  <Image
                    src={bannerPreview}
                    alt="Banner preview"
                    fill
                    className="object-cover"
                    sizes="(max-width: 768px) 100vw, 50vw"
                  />
                </div>
                <button
                  type="button"
                  onClick={removeBannerImage}
                  className="absolute top-2 right-2 p-1 bg-red-600 text-white rounded-full hover:bg-red-700"
                >
                  <XMarkIcon className="h-4 w-4" />
                </button>
                <div className="mt-2">
                  <label className="block text-sm font-medium text-gray-700">
                    Alt Text
                  </label>
                  <input
                    type="text"
                    value={bannerAlt}
                    onChange={(e) => setBannerAlt(e.target.value)}
                    placeholder="Describe the image for accessibility"
                    className="mt-1 block w-full px-3 py-2 text-sm rounded-md border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500"
                  />
                </div>
              </div>
            ) : (
              <div className="border-2 border-dashed border-gray-300 rounded-lg p-6 text-center hover:border-gray-400 transition-colors">
                <PhotoIcon className="mx-auto h-12 w-12 text-gray-400" />
                <div className="mt-4">
                  <button
                    type="button"
                    onClick={openMediaLibrary}
                    className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                  >
                    <CloudArrowUpIcon className="h-4 w-4 mr-2" />
                    Select Banner Image
                  </button>
                </div>
                <p className="text-xs text-gray-500 mt-2">
                  Browse existing images or upload new ones. Recommended size: 1200x400px
                </p>
              </div>
            )}
            
            <input
              ref={fileInputRef}
              type="file"
              accept="image/*"
              onChange={handleImageUpload}
              className="hidden"
            />
          </div>
        </ModalBody>

        <ModalFooter>
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 text-sm font-medium text-gray-700 hover:text-gray-500"
          >
            Cancel
          </button>
          <button
            type="submit"
            disabled={loading || !formData.name || !formData.conferenceId}
            className="px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-[#F5821F] hover:bg-[#e0741c] disabled:bg-gray-300 disabled:cursor-not-allowed"
          >
            {loading ? 'Saving...' : (church ? 'Update' : 'Create')} Church
          </button>
        </ModalFooter>
      </form>
    </Modal>

    <MediaLibraryModal
      isOpen={isMediaLibraryOpen}
      onClose={() => setIsMediaLibraryOpen(false)}
      onSelect={handleMediaSelect}
      title="Select Banner Image"
      allowedTypes={['banner', 'gallery']}
      category="church"
      type="banner"
    />
  </>
  );
}